import db, { LOADS_TABLE } from "./db.js";
import { PutCommand } from "@aws-sdk/lib-dynamodb";

function futureDate(daysOut, hour = 8) {
  const d = new Date();
  d.setDate(d.getDate() + daysOut);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString().slice(0, 19);
}

function deliveryDate(daysOut, hour = 8, transitHours = 12) {
  const d = new Date();
  d.setDate(d.getDate() + daysOut);
  d.setHours(hour + transitHours, 0, 0, 0);
  return d.toISOString().slice(0, 19);
}

const LOADS = [
  {
    load_id: "LD-1001",
    origin: "Chicago",
    destination: "Dallas",
    pickup_datetime: futureDate(1, 8),
    delivery_datetime: deliveryDate(1, 8, 18),
    equipment_type: "Dry Van",
    loadboard_rate: 2850,
    notes: "Dock-to-dock, no touch freight",
    weight: 42000,
    commodity_type: "Consumer Electronics",
    num_of_pieces: 24,
    miles: 920,
    dimensions: "48x40x48 pallets",
    lat: 41.8781,
    lng: -87.6298,
    status: "available",
  },
  {
    load_id: "LD-1002",
    origin: "Atlanta",
    destination: "Miami",
    pickup_datetime: futureDate(1, 6),
    delivery_datetime: deliveryDate(1, 6, 14),
    equipment_type: "Reefer",
    loadboard_rate: 1800,
    notes: "Temperature must stay 34-38°F",
    weight: 38000,
    commodity_type: "Frozen Foods",
    num_of_pieces: 18,
    miles: 662,
    dimensions: "48x40x60 pallets",
    lat: 33.7490,
    lng: -84.3880,
    status: "available",
  },
  {
    load_id: "LD-1003",
    origin: "Los Angeles",
    destination: "Phoenix",
    pickup_datetime: futureDate(2, 10),
    delivery_datetime: deliveryDate(2, 10, 12),
    equipment_type: "Flatbed",
    loadboard_rate: 1400,
    notes: "Tarps required, oversized permit on file",
    weight: 45000,
    commodity_type: "Steel Beams",
    num_of_pieces: 6,
    miles: 373,
    dimensions: "40ft lengths",
    lat: 34.0522,
    lng: -118.2437,
    status: "available",
  },
  {
    load_id: "LD-1004",
    origin: "Houston",
    destination: "Memphis",
    pickup_datetime: futureDate(1, 14),
    delivery_datetime: deliveryDate(1, 14, 20),
    equipment_type: "Dry Van",
    loadboard_rate: 1950,
    notes: "FCFS appointment, lumper included",
    weight: 35000,
    commodity_type: "Paper Products",
    num_of_pieces: 30,
    miles: 586,
    dimensions: "48x40x48 pallets",
    lat: 29.7604,
    lng: -95.3698,
    status: "available",
  },
  {
    load_id: "LD-1005",
    origin: "Nashville",
    destination: "Charlotte",
    pickup_datetime: futureDate(3, 7),
    delivery_datetime: deliveryDate(3, 7, 11),
    equipment_type: "Dry Van",
    loadboard_rate: 1200,
    notes: "Driver assist unload",
    weight: 28000,
    commodity_type: "Auto Parts",
    num_of_pieces: 40,
    miles: 410,
    dimensions: "Mixed cartons",
    lat: 36.1627,
    lng: -86.7816,
    status: "available",
  },
  {
    load_id: "LD-1006",
    origin: "Denver",
    destination: "Kansas City",
    pickup_datetime: futureDate(2, 6),
    delivery_datetime: deliveryDate(2, 6, 14),
    equipment_type: "Reefer",
    loadboard_rate: 1650,
    notes: "Continuous temp monitoring required",
    weight: 40000,
    commodity_type: "Pharmaceuticals",
    num_of_pieces: 12,
    miles: 604,
    dimensions: "48x40x48 pallets",
    lat: 39.7392,
    lng: -104.9903,
    status: "available",
  },
  {
    load_id: "LD-1007",
    origin: "Seattle",
    destination: "Portland",
    pickup_datetime: futureDate(1, 9),
    delivery_datetime: deliveryDate(1, 9, 5),
    equipment_type: "Flatbed",
    loadboard_rate: 750,
    notes: "Chains and binders provided",
    weight: 48000,
    commodity_type: "Lumber",
    num_of_pieces: 1,
    miles: 174,
    dimensions: "24ft bundles",
    lat: 47.6062,
    lng: -122.3321,
    status: "available",
  },
  {
    load_id: "LD-1008",
    origin: "Detroit",
    destination: "Indianapolis",
    pickup_datetime: futureDate(3, 12),
    delivery_datetime: deliveryDate(3, 12, 8),
    equipment_type: "Dry Van",
    loadboard_rate: 1100,
    notes: "No hazmat, floor loaded",
    weight: 32000,
    commodity_type: "Automotive Components",
    num_of_pieces: 50,
    miles: 280,
    dimensions: "Mixed cartons and crates",
    lat: 42.3314,
    lng: -83.0458,
    status: "available",
  },
  {
    load_id: "LD-1009",
    origin: "New York",
    destination: "Boston",
    pickup_datetime: futureDate(2, 5),
    delivery_datetime: deliveryDate(2, 5, 7),
    equipment_type: "Dry Van",
    loadboard_rate: 950,
    notes: "Tight delivery window, must be on time",
    weight: 22000,
    commodity_type: "Retail Goods",
    num_of_pieces: 35,
    miles: 215,
    dimensions: "48x40x48 pallets",
    lat: 40.7128,
    lng: -74.0060,
    status: "available",
  },
  {
    load_id: "LD-1010",
    origin: "San Antonio",
    destination: "El Paso",
    pickup_datetime: futureDate(4, 8),
    delivery_datetime: deliveryDate(4, 8, 14),
    equipment_type: "Dry Van",
    loadboard_rate: 1500,
    notes: "Cross-border prep, BOL must be clean",
    weight: 38000,
    commodity_type: "Building Materials",
    num_of_pieces: 20,
    miles: 550,
    dimensions: "48x40x72 pallets",
    lat: 29.4241,
    lng: -98.4936,
    status: "available",
  },
  {
    load_id: "LD-1011",
    origin: "Minneapolis",
    destination: "Chicago",
    pickup_datetime: futureDate(1, 7),
    delivery_datetime: deliveryDate(1, 7, 11),
    equipment_type: "Reefer",
    loadboard_rate: 1350,
    notes: "Frozen, -10°F required",
    weight: 41000,
    commodity_type: "Frozen Meat",
    num_of_pieces: 22,
    miles: 410,
    dimensions: "48x40x48 pallets",
    lat: 44.9778,
    lng: -93.2650,
    status: "available",
  },
  {
    load_id: "LD-1012",
    origin: "Jacksonville",
    destination: "Savannah",
    pickup_datetime: futureDate(3, 10),
    delivery_datetime: deliveryDate(3, 10, 5),
    equipment_type: "Flatbed",
    loadboard_rate: 650,
    notes: "Port pickup, chassis provided",
    weight: 44000,
    commodity_type: "Heavy Machinery",
    num_of_pieces: 2,
    miles: 140,
    dimensions: "20ft containers",
    lat: 30.3322,
    lng: -81.6557,
    status: "available",
  },
  {
    load_id: "LD-1013",
    origin: "Orlando",
    destination: "Atlanta",
    pickup_datetime: futureDate(2, 8),
    delivery_datetime: deliveryDate(2, 8, 16),
    equipment_type: "Dry Van",
    loadboard_rate: 1100,
    notes: "Live load, live unload",
    weight: 40000,
    commodity_type: "Beverages",
    num_of_pieces: 20,
    miles: 440,
    dimensions: "48x40x48 pallets",
    lat: 28.5383,
    lng: -81.3792,
    status: "available",
  },
  {
    load_id: "LD-1014",
    origin: "Columbus",
    destination: "Chicago",
    pickup_datetime: futureDate(2, 14),
    delivery_datetime: deliveryDate(2, 14, 16),
    equipment_type: "Dry Van",
    loadboard_rate: 850,
    notes: "Drop trailer at delivery",
    weight: 32000,
    commodity_type: "Packaging Materials",
    num_of_pieces: 30,
    miles: 350,
    dimensions: "48x40x60 pallets",
    lat: 39.9612,
    lng: -82.9988,
    status: "available",
  },
  {
    load_id: "LD-1015",
    origin: "Philadelphia",
    destination: "Pittsburgh",
    pickup_datetime: futureDate(4, 9),
    delivery_datetime: deliveryDate(4, 9, 8),
    equipment_type: "Reefer",
    loadboard_rate: 900,
    notes: "Keep at 35°F",
    weight: 35000,
    commodity_type: "Produce",
    num_of_pieces: 18,
    miles: 305,
    dimensions: "48x40x48 pallets",
    lat: 39.9526,
    lng: -75.1652,
    status: "available",
  },
  {
    load_id: "LD-1016",
    origin: "Salt Lake City",
    destination: "Denver",
    pickup_datetime: futureDate(3, 7),
    delivery_datetime: deliveryDate(3, 7, 20),
    equipment_type: "Flatbed",
    loadboard_rate: 1350,
    notes: "Tarping required",
    weight: 46000,
    commodity_type: "Construction Materials",
    num_of_pieces: 10,
    miles: 520,
    dimensions: "Various lengths",
    lat: 40.7608,
    lng: -111.8910,
    status: "available",
  },
  {
    load_id: "LD-1017",
    origin: "Charlotte",
    destination: "Richmond",
    pickup_datetime: futureDate(1, 11),
    delivery_datetime: deliveryDate(1, 11, 10),
    equipment_type: "Dry Van",
    loadboard_rate: 750,
    notes: "No touch freight",
    weight: 25000,
    commodity_type: "Textiles",
    num_of_pieces: 40,
    miles: 290,
    dimensions: "Mixed cartons",
    lat: 35.2271,
    lng: -80.8431,
    status: "available",
  },
  {
    load_id: "LD-1018",
    origin: "Dallas",
    destination: "Oklahoma City",
    pickup_datetime: futureDate(3, 13),
    delivery_datetime: deliveryDate(3, 13, 10),
    equipment_type: "Dry Van",
    loadboard_rate: 900,
    notes: "Strict appointment times",
    weight: 38000,
    commodity_type: "Plastics",
    num_of_pieces: 22,
    miles: 340,
    dimensions: "48x40x48 pallets",
    lat: 32.7767,
    lng: -96.7970,
    status: "available",
  },
  {
    load_id: "LD-1019",
    origin: "Las Vegas",
    destination: "Los Angeles",
    pickup_datetime: futureDate(5, 8),
    delivery_datetime: deliveryDate(5, 8, 6),
    equipment_type: "Reefer",
    loadboard_rate: 800,
    notes: "Protect from freeze",
    weight: 30000,
    commodity_type: "Beverages",
    num_of_pieces: 26,
    miles: 270,
    dimensions: "48x40x48 pallets",
    lat: 36.1699,
    lng: -115.1398,
    status: "available",
  },
  {
    load_id: "LD-1020",
    origin: "St. Louis",
    destination: "Louisville",
    pickup_datetime: futureDate(2, 15),
    delivery_datetime: deliveryDate(2, 15, 10),
    equipment_type: "Flatbed",
    loadboard_rate: 850,
    notes: "Straps only, no tarps",
    weight: 42000,
    commodity_type: "Machinery",
    num_of_pieces: 4,
    miles: 260,
    dimensions: "Large crates",
    lat: 38.6270,
    lng: -90.1994,
    status: "available",
  },
  {
    load_id: "LD-1021",
    origin: "Chicago",
    destination: "Milwaukee",
    pickup_datetime: futureDate(1, 6),
    delivery_datetime: deliveryDate(1, 6, 4),
    equipment_type: "Dry Van",
    loadboard_rate: 550,
    notes: "Quick turn, same-day delivery",
    weight: 20000,
    commodity_type: "Food & Beverage",
    num_of_pieces: 16,
    miles: 92,
    dimensions: "48x40x48 pallets",
    lat: 41.8781,
    lng: -87.6298,
    status: "available",
  },
  {
    load_id: "LD-1022",
    origin: "Houston",
    destination: "New Orleans",
    pickup_datetime: futureDate(2, 7),
    delivery_datetime: deliveryDate(2, 7, 8),
    equipment_type: "Reefer",
    loadboard_rate: 1250,
    notes: "Must maintain 32°F, seafood load",
    weight: 36000,
    commodity_type: "Seafood",
    num_of_pieces: 14,
    miles: 348,
    dimensions: "48x40x48 pallets",
    lat: 29.7604,
    lng: -95.3698,
    status: "available",
  },
  {
    load_id: "LD-1023",
    origin: "Atlanta",
    destination: "Nashville",
    pickup_datetime: futureDate(1, 13),
    delivery_datetime: deliveryDate(1, 13, 6),
    equipment_type: "Dry Van",
    loadboard_rate: 950,
    notes: "Live unload, 2-hour window",
    weight: 34000,
    commodity_type: "Home Appliances",
    num_of_pieces: 12,
    miles: 250,
    dimensions: "Large cartons",
    lat: 33.7490,
    lng: -84.3880,
    status: "available",
  },
  {
    load_id: "LD-1024",
    origin: "San Francisco",
    destination: "Sacramento",
    pickup_datetime: futureDate(1, 10),
    delivery_datetime: deliveryDate(1, 10, 4),
    equipment_type: "Flatbed",
    loadboard_rate: 600,
    notes: "No tarps needed, open steel",
    weight: 47000,
    commodity_type: "Steel Coils",
    num_of_pieces: 3,
    miles: 88,
    dimensions: "Coils, 48in diameter",
    lat: 37.7749,
    lng: -122.4194,
    status: "available",
  },
  {
    load_id: "LD-1025",
    origin: "Dallas",
    destination: "Houston",
    pickup_datetime: futureDate(1, 15),
    delivery_datetime: deliveryDate(1, 15, 5),
    equipment_type: "Dry Van",
    loadboard_rate: 750,
    notes: "Drop and hook at both ends",
    weight: 40000,
    commodity_type: "Consumer Goods",
    num_of_pieces: 28,
    miles: 240,
    dimensions: "48x40x48 pallets",
    lat: 32.7767,
    lng: -96.7970,
    status: "available",
  },
  {
    load_id: "LD-1026",
    origin: "Phoenix",
    destination: "Albuquerque",
    pickup_datetime: futureDate(4, 6),
    delivery_datetime: deliveryDate(4, 6, 10),
    equipment_type: "Dry Van",
    loadboard_rate: 1200,
    notes: "No driver assist, dock high",
    weight: 39000,
    commodity_type: "Electronics",
    num_of_pieces: 32,
    miles: 420,
    dimensions: "48x40x48 pallets",
    lat: 33.4484,
    lng: -112.0740,
    status: "available",
  },
  {
    load_id: "LD-1027",
    origin: "Memphis",
    destination: "Little Rock",
    pickup_datetime: futureDate(2, 11),
    delivery_datetime: deliveryDate(2, 11, 4),
    equipment_type: "Reefer",
    loadboard_rate: 650,
    notes: "Keep at 40°F, dairy products",
    weight: 33000,
    commodity_type: "Dairy",
    num_of_pieces: 20,
    miles: 135,
    dimensions: "48x40x48 pallets",
    lat: 35.1495,
    lng: -90.0490,
    status: "available",
  },
  {
    load_id: "LD-1028",
    origin: "Denver",
    destination: "Albuquerque",
    pickup_datetime: futureDate(5, 8),
    delivery_datetime: deliveryDate(5, 8, 10),
    equipment_type: "Flatbed",
    loadboard_rate: 1450,
    notes: "Oversized load, escort required",
    weight: 48000,
    commodity_type: "Wind Turbine Blades",
    num_of_pieces: 1,
    miles: 450,
    dimensions: "80ft length",
    lat: 39.7392,
    lng: -104.9903,
    status: "available",
  },
  {
    load_id: "LD-1029",
    origin: "Chicago",
    destination: "St. Louis",
    pickup_datetime: futureDate(2, 9),
    delivery_datetime: deliveryDate(2, 9, 6),
    equipment_type: "Dry Van",
    loadboard_rate: 800,
    notes: "FCFS, arrive before noon",
    weight: 37000,
    commodity_type: "Canned Goods",
    num_of_pieces: 24,
    miles: 297,
    dimensions: "48x40x48 pallets",
    lat: 41.8781,
    lng: -87.6298,
    status: "available",
  },
  {
    load_id: "LD-1030",
    origin: "Miami",
    destination: "Jacksonville",
    pickup_datetime: futureDate(3, 6),
    delivery_datetime: deliveryDate(3, 6, 8),
    equipment_type: "Reefer",
    loadboard_rate: 1100,
    notes: "Frozen, must be -5°F, USDA seal required",
    weight: 42000,
    commodity_type: "Frozen Seafood",
    num_of_pieces: 18,
    miles: 345,
    dimensions: "48x40x48 pallets",
    lat: 25.7617,
    lng: -80.1918,
    status: "available",
  },
];

async function seedAll() {
  console.log("Seeding loads to DynamoDB...");
  for (const load of LOADS) {
    try {
      await db.send(new PutCommand({
        TableName: LOADS_TABLE,
        Item: load
      }));
    } catch (err) {
      console.error(`Failed to seed load ${load.load_id}:`, err);
    }
  }
  console.log(`Seeded ${LOADS.length} loads`);
}

seedAll();
